resources:
- name: sourcecode
  type: git
  check_every: 600h
  webhook_token: runit
  source:
    uri: https://github.com/jshingler/concourse-webhook.git
    branch: master

jobs:
- name: hello-world
  plan:
  - get: sourcecode
  - task: say-hello-webhook
    file: sourcecode/tasks/helloworld.yml
