---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
  - name: sourcecode

outputs:
  - name: build

run:
  path: echo
  args: ["Hello, JAVA!"]
